### ISSUE TITLE
Update to Node.js 16

### ISSUE THREAD

**Issue by vertrou** [idealo/setup-aaga-credentials-action#136]
When using the action lately, I get the following warning in my GitHub workflows:

```
Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: Sibz/github-status-action, Sibz/github-status-action
```

Could you please update the project so that it uses Node.js 16?

I also get warnings the the methods set-output is deprecated.
```
Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
```
Could you please update the project so that it uses the new method?

**Comment by mgerlach** [comment]
@vertrou I will not upgrade the Action as it has itself been deprecated for a long time and will be disabled next year. An announcement will be made after Black Friday. Please switch to the official way of authenticating GH Actions with AWS as described here: https://confluence.eu.idealo.com/display/PTN/How+to+authenticate+from+GitHub+to+AWS
